// SAMPLE USER DATA
{
    "userData": [
        {
            "firstName": "John",
            "lastName": "Doe",
            "email": "john.doe@example.com",
            "phone": "1234567890",
            "password": "password123",
            "userType": "user",
            "isActive": true,
        },
        {
            "firstName": "Jane",
            "lastName": "Smith",
            "email": "jane.smith@example.com",
            "phone": "0987654321",
            "password": "password456",
            "userType": "admin",
            "isActive": true,
        },
        {
            "firstName": "Michael",
            "lastName": "Johnson",
            "email": "michael.johnson@example.com",
            "phone": "1112223333",
            "password": "password789",
            "userType": "seller",
            "isActive": false,
        },
        {
            "firstName": "Emily",
            "lastName": "Brown",
            "email": "emily.brown@example.com",
            "phone": "5556667777",
            "password": "passwordabc",
            "userType": "user",
            "isActive": true,
        },
        {
            "firstName": "William",
            "lastName": "Wilson",
            "email": "william.wilson@example.com",
            "phone": "7778889999",
            "password": "passwordxyz",
            "userType": "admin",
            "isActive": true,
        },
        {
            "firstName": "Sophia",
            "lastName": "Garcia",
            "email": "sophia.garcia@example.com",
            "phone": "3334445555",
            "password": "password123",
            "userType": "seller",
            "isActive": false,
        },
        {
            "firstName": "David",
            "lastName": "Martinez",
            "email": "david.martinez@example.com",
            "phone": "6667778888",
            "password": "password456",
            "userType": "user",
            "isActive": true,
        },
        {
            "firstName": "Olivia",
            "lastName": "Lopez",
            "email": "olivia.lopez@example.com",
            "phone": "8889990000",
            "password": "password789",
            "userType": "admin",
            "isActive": true,
        },
        {
            "firstName": "Daniel",
            "lastName": "Gonzalez",
            "email": "daniel.gonzalez@example.com",
            "phone": "2223334444",
            "password": "passwordabc",
            "userType": "user",
            "isActive": true,
        },
        {
            "firstName": "Mia",
            "lastName": "Rodriguez",
            "email": "mia.rodriguez@example.com",
            "phone": "9990001111",
            "password": "passwordxyz",
            "userType": "seller",
            "isActive": false,
        }
    ]
}

// SAMPLE PRODUCT DATA

// 1. Create an Admin or Seller Account
// - Log in to your MongoDB Database (e.g., MongoDB Compass or MongoDB Atlas).
// - Insert or create a user with admin or seller type privileges. Ensure that the user has the necessary roles and permissions to manage products.

// 2. Obtain the _id
// - Find the `_id` of the admin or seller account you created in the database.
// - The `_id` field is a unique identifier automatically generated by MongoDB for each document.

// 3. Update the Sample Data
// - Replace the `"sellerId"` field in your sample product data with the `_id` of the admin or seller account you obtained from the database.

{
    "sampleProducts": [
        {
            "title": "Eternal Essence",
            "age": "Adult",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 1 description.",
            "price": 65,
            "category": "Litter",
            "quantity": 20,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Harmony Haven",
            "age": "Kitten",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 5 description.",
            "price": 60,
            "category": "Litter",
            "quantity": 23,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Elysian Eden",
            "age": "All",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 9 description.",
            "price": 68,
            "category": "Litter",
            "quantity": 19,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Glistening Glade",
            "age": "Adult",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 13 description.",
            "price": 85,
            "category": "Litter",
            "quantity": 23,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Divine Destiny",
            "age": "Kitten",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 17 description.",
            "price": 53,
            "category": "Litter",
            "quantity": 20,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Enigma Essence",
            "age": "All",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 21 description.",
            "price": 57,
            "category": "Litter",
            "quantity": 25,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Tranquil Tide",
            "age": "Adult",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 25 description.",
            "price": 55,
            "category": "Litter",
            "quantity": 20,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Mystical Moonlight",
            "age": "Kitten",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 29 description.",
            "price": 50,
            "category": "Litter",
            "quantity": 24,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Zen Zenith",
            "age": "All",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 33 description.",
            "price": 62,
            "category": "Litter",
            "quantity": 21,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Oasis Opulence",
            "age": "Adult",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 37 description.",
            "price": 75,
            "category": "Litter",
            "quantity": 19,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Eternal Echo",
            "age": "Kitten",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 41 description.",
            "price": 50,
            "category": "Litter",
            "quantity": 18,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Elysian Eden",
            "age": "All",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 45 description.",
            "price": 75,
            "category": "Litter",
            "quantity": 16,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Glistening Glade",
            "age": "Adult",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 49 description.",
            "price": 68,
            "category": "Litter",
            "quantity": 22,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Divine Destiny",
            "age": "Kitten",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 53 description.",
            "price": 70,
            "category": "Litter",
            "quantity": 18,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Enigma Essence",
            "age": "All",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 57 description.",
            "price": 70,
            "category": "Litter",
            "quantity": 19,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Tranquil Tide",
            "age": "Adult",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 61 description.",
            "price": 65,
            "category": "Litter",
            "quantity": 20,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Mystical Moonlight",
            "age": "Kitten",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 65 description.",
            "price": 72,
            "category": "Litter",
            "quantity": 21,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Zen Zenith",
            "age": "All",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 69 description.",
            "price": 47,
            "category": "Litter",
            "quantity": 25,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Oasis Opulence",
            "age": "Adult",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 73 description.",
            "price": 68,
            "category": "Litter",
            "quantity": 22,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Eternal Echo",
            "age": "Kitten",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 77 description.",
            "price": 60,
            "category": "Litter",
            "quantity": 26,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Elysian Eden",
            "age": "All",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 81 description.",
            "price": 65,
            "category": "Litter",
            "quantity": 24,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Glistening Glade",
            "age": "Adult",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 85 description.",
            "price": 65,
            "category": "Litter",
            "quantity": 27,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Divine Destiny",
            "age": "Kitten",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 89 description.",
            "price": 50,
            "category": "Litter",
            "quantity": 20,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Enigma Essence",
            "age": "All",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 93 description.",
            "price": 80,
            "category": "Litter",
            "quantity": 18,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
        {
            "title": "Tranquil Tide",
            "age": "Adult",
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Product 97 description.",
            "price": 48,
            "category": "Litter",
            "quantity": 25,
            "sellerId": "66c88e6d64010bf2224849f7"
        },
    ]
}